#ifndef INS_H
#define INS_H

inline void IMPLEMENTATION_LDA_IMMEDIATE    ();
inline void IMPLEMENTATION_LDA_ZERO_PAGE    ();
inline void IMPLEMENTATION_LDA_ZERO_PAGE_X  ();
inline void IMPLEMENTATION_LDA_ABSOLUTE     ();
inline void IMPLEMENTATION_LDA_ABSOLUTE_X   ();
inline void IMPLEMENTATION_LDA_ABSOLUTE_Y   ();
inline void IMPLEMENTATION_LDA_INDIRECT_X();
inline void IMPLEMENTATION_LDA_INDIRECT_Y();

#endif
